@startuml deployment
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2

!include DEVICONS/postgresql.puml
!include DEVICONS/docker.puml
!include DEVICONS/redis.puml
!include DEVICONS2/nestjs.puml
!include ../sprites/govuk.puml

Deployment_Node(gpaas, "GPaaS", "GOV.UK PaaS", $sprite="govuk"){
  Deployment_Node(webappDocker, "Docker container", $sprite="docker") {
    Container(webApp, "Web Application", "NestJS", $sprite="nestjs")
  }

  ContainerDb_Ext(postgres, "PostgreSQL database", "PostgreSQL", $sprite="postgresql")
  ContainerDb_Ext(redis, "Redis database", "Redis", $sprite="redis")

  BiRel(webApp, postgres, "Read/write")
  BiRel(webApp, redis, "Read/write")
}

SHOW_LEGEND()
@enduml
