export enum UserPermission {
  CreateUser = 'createUser',
  EditUser = 'editUser',
  DeleteUser = 'deleteUser',
  CreateOrganisation = 'createOrganisation',
  EditOrganisation = 'editOrganisation',
  DeleteOrganisation = 'deleteOrganisation',
  PublishOrganisation = 'publishOrganisation',
  CreateProfession = 'createProfession',
  DeleteProfession = 'deleteProfession',
  EditProfession = 'editProfession',
  UploadDecisionData = 'uploadDecisionData',
  DownloadDecisionData = 'downloadDecisionData',
  ViewDecisionData = 'viewDecisionData',
}
