@startuml container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2

!include DEVICONS/postgresql.puml
!include DEVICONS/redis.puml
!include DEVICONS2/nestjs.puml
!include ../sprites/govuk.puml
!include ../sprites/auth0.puml

Person(public, "Public User", "People searching for information on regulated professions")
Person(regulators, "Regulatory Authority", "Users who maintain their information in the system")
Person(beis, "Service Owners", "Users who manage access and approve changes")

System_Boundary(rpr, "Reguatory Providers Register") {
  Container(nestApplication, "NestJS Web application", "NestJS", $sprite="nestjs")
  ContainerDb(postgres, "PostgreSQL database", "PostgreSQL", $sprite="postgresql")
  ContainerDb(redis, "Redis database", "Redis", $sprite="redis")

  Rel(nestApplication, postgres, "Read/write")
  Rel(nestApplication, redis, "Sends jobs")
  Rel(redis, nestApplication, "Picks jobs from the queue")
}

System_Ext(notify, "GOV.UK Notify", $sprite="govuk")
System_Ext(auth0, "Auth0", $sprite="auth0")

Rel(notify, regulators, "Sends notifications", "email")
Rel(notify, beis, "Sends notifications", "email")

Rel(regulators, auth0, "Logs in", "HTTPS/OAuth2")
Rel(beis, auth0, "Logs in", "HTTPS/OAuth2")

Rel(nestApplication, notify, "API calls", "HTTPS")
Rel_L(nestApplication, auth0, "API calls", "HTTPS")

Rel(public, nestApplication, "Uses")
Rel(regulators, nestApplication, "Uses")
Rel(beis, nestApplication, "Uses")

Rel(auth0, nestApplication, "Sends user authentication details", "HTTPS/OAuth2")

SHOW_LEGEND()
@enduml
