#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

echo "==> Installing application dependencies..."

nodenv install --skip-existing

if ! [[ -f $(which npm) ]]; then
    nodenv init
    exit 1
fi

npm install

echo "==> Building..."
npm run build

echo "==> Building assets..."

npm run build:assets

echo "==> Running OpenSearch in the background..."

brew services start opensearch

echo "==> Seeding database..."

npm run seed

echo "==> Running Redis in the background..."

redis-server --daemonize yes
