#!/bin/sh

# Setup environment for CI to run tests. This is primarily designed to run on
# the continuous integration server.

set -e

export DATABASE_URL="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB"

cd "$(dirname "$0")/.."

echo "==> Installing dependencies..."

npm ci

echo "==> Running database migrations"

npm run typeorm migration:run

echo "==> Building assets..."

npm run build:assets

script/test
