#!/bin/sh

printf "Waiting for deploy."
current_sha=$(git rev-parse HEAD)

while :
do
  printf "."
  deployed_sha=$(curl -s "$HEALTH_CHECK_URL" | jq -r '.git_sha')
  if [ "$deployed_sha" = "$current_sha" ]; then
    break
  fi
  sleep 10
done
