#!/bin/bash

echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin

docker build --target web \
         --build-arg current_sha="$GITHUB_SHA" \
         --build-arg time_of_build="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
         -t "ghcr.io/UKGovernmentBEIS/regulated-professions-register:$DOCKER_TAG" \
         .
         docker push "ghcr.io/UKGovernmentBEIS/regulated-professions-register:$DOCKER_TAG"
