#!/bin/bash

docker build --target web \
         --build-arg current_sha="$GITHUB_SHA" \
         --build-arg time_of_build="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
         -t "ghcr.io/ukgovernmentbeis/regulated-professions-register:$DOCKER_TAG" \
         .
         docker push "ghcr.io/ukgovernmentbeis/regulated-professions-register:$DOCKER_TAG"
