#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

cd "$(dirname "$0")/.."

app_name=$(basename "$PWD")
dev_db="$app_name-development"
test_db="$app_name-test"

if ! brew bundle check >/dev/null 2>&1; then
  echo "==> Installing Homebrew dependencies…"
  brew bundle install --verbose
fi

echo "==> Dropping and recreating the database..."

dropdb "$dev_db" > /dev/null 2>&1 || true
dropdb "$test_db" > /dev/null 2>&1 || true

createdb "$dev_db"
createdb "$test_db"

env_file=$(cat .env.example)

if [ ! -f .env.development ]; then
  echo "==> Creating env file for dev..."
  dev_env_file=$(sed "s/\$DATABASE_NAME/$dev_db/g"  < ".env.example")
  echo "$dev_env_file" > .env.development
fi

if [ ! -f .env.test ]; then
  echo "==> Creating env file for test..."
  test_env_file=$(sed "s/\$DATABASE_NAME/$dev_db/g"  < ".env.example")
  echo "$test_env_file" > .env.test
fi

script/bootstrap

