#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

cd "$(dirname "$0")/.."

app_name=$(basename "$PWD")
dev_db="$app_name-development"
test_db="$app_name-test"

if ! brew bundle check >/dev/null 2>&1; then
  echo "==> Installing Homebrew dependencies…"
  brew bundle install --verbose --no-lock
fi

echo "==> Dropping and recreating the database..."

dropdb "$dev_db" > /dev/null 2>&1 || true
dropdb "$test_db" > /dev/null 2>&1 || true

createdb "$dev_db"
createdb "$test_db"

echo "==> Creating env files for dev and test..."

echo "DATABASE_URL=postgres://postgres@localhost:5432/$dev_db" > .env.development
echo "DATABASE_URL=postgres://postgres@localhost:5432/$test_db" > .env.test

echo "==> Installing application dependencies..."

nodenv install --skip-existing
npm install

echo "==> Building assets..."

npm run build:assets

