#!/bin/sh

# script/test: Run the test suite for the application.

set -e

echo "==> Checking code for Prettier errors"

npm run format:check

echo "==> Linting the code"

npm run lint

echo "==> Running unit tests..."

npm run test

echo "==> Running e2e tests..."

npm run test:e2e
