#!/bin/sh

# Setup environment for CI to run tests. This is primarily designed to run on
# the continuous integration server.

set -e

cd "$(dirname "$0")/../.."

docker build --target dependencies -t app_dependencies:latest .
docker build --target web -t app_web:latest .
docker-compose -f docker-compose.ci.yml -p app build
