name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  HOST_URL: ${{ secrets.HOST_URL }}
  OKTA_ORG_URL: ${{ secrets.OKTA_ORG_URL }}
  OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
  OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
  OKTA_TOKEN: ${{ secrets.OKTA_TOKEN }}
  OKTA_REDIRECT_URL: ${{ secrets.OKTA_REDIRECT_URL }}
  APP_SECRET: ${{ secrets.APP_SECRET }}
  AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
  AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: cache-docker
        uses: actions/cache@v2
        with:
          path: /tmp/docker-save
          key: docker-save-${{ hashFiles('Dockerfile', 'package-lock.json') }}

      - if: steps.cache-docker.outputs.cache-hit == 'true'
        name: Load cached Docker image
        run: docker load -i /tmp/docker-save/snapshot.tar || true

      - name: Build
        run: script/ci/cibuild

      - name: Test
        run: script/ci/test

      - if: always() && steps.cache-docker.outputs.cache-hit != 'true'
        name: Prepare Docker cache
        run: mkdir -p /tmp/docker-save && docker save app_test:latest -o
          /tmp/docker-save/snapshot.tar && ls -lh /tmp/docker-save
