name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  HOST_URL: ${{ secrets.HOST_URL }}
  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  APP_SECRET: ${{ secrets.APP_SECRET }}
  ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  REGISTRAR_USERNAME: ${{ secrets.REGISTRAR_USERNAME }}
  REGISTRAR_PASSWORD: ${{ secrets.REGISTRAR_PASSWORD }}
  EDITOR_USERNAME: ${{ secrets.EDITOR_USERNAME }}
  EDITOR_PASSWORD: ${{ secrets.EDITOR_PASSWORD }}
  ORGADMIN_USERNAME: ${{ secrets.ORGADMIN_USERNAME }}
  ORGADMIN_PASSWORD: ${{ secrets.ORGADMIN_PASSWORD }}
  ORGEDITOR_USERNAME: ${{ secrets.ORGEDITOR_USERNAME }}
  ORGEDITOR_PASSWORD: ${{ secrets.ORGEDITOR_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: app_test:latest
          build-args: NODE_ENV=test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test
        id: test
        run: script/ci/test

      - name: Upload end-to-end-test screenshots
        if: failure() && steps.Test.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: end-to-end-test-screenshots
          path: cypress/screenshots/
          retention-days: 14

      - name: Upload end-to-end-test videos
        if: failure() && steps.Test.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: end-to-end-test-videos
          path: cypress/videos/
          retention-days: 14
