name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - name: Run CI
        run: script/ci
        env:
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci-test
