name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  HOST_URL: ${{ secrets.HOST_URL }}
  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  APP_SECRET: ${{ secrets.APP_SECRET }}
  ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  REGISTRAR_USERNAME: ${{ secrets.REGISTRAR_USERNAME }}
  REGISTRAR_PASSWORD: ${{ secrets.REGISTRAR_PASSWORD }}
  EDITOR_USERNAME: ${{ secrets.EDITOR_USERNAME }}
  EDITOR_PASSWORD: ${{ secrets.EDITOR_PASSWORD }}
  ORGADMIN_USERNAME: ${{ secrets.ORGADMIN_USERNAME }}
  ORGADMIN_PASSWORD: ${{ secrets.ORGADMIN_PASSWORD }}
  ORGEDITOR_USERNAME: ${{ secrets.ORGEDITOR_USERNAME }}
  ORGEDITOR_PASSWORD: ${{ secrets.ORGEDITOR_PASSWORD }}
  NODE_ENV: test
  CI: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: cache-docker
        uses: actions/cache@v2
        with:
          path: /tmp/docker-save
          key: docker-save-${{ hashFiles('Dockerfile', 'package-lock.json') }}

      - if: steps.cache-docker.outputs.cache-hit == 'true'
        name: Load cached Docker image
        run: docker load -i /tmp/docker-save/snapshot.tar || true

      - name: Build
        run: script/ci/cibuild

      - name: Save Docker image
        run: |
          mkdir -p /tmp/docker-save
          docker save app_test:latest | gzip > /tmp/docker-save/snapshot.tar.gz

      - uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: /tmp/docker-save/snapshot.tar.gz
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Docker Image
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: /tmp/docker-save/snapshot.tar.gz

      - name: Load Docker Image
        run: |
          cd /tmp/docker-save
          docker load --input snapshot.tar.gz

      - name: Test
        id: test
        run: script/ci/e2e
        env:
          MATRIX: ${{ matrix.container }}
